networks:
  instashop-net:
    driver: bridge

volumes:
  kafka1_data:
  kafka2_data:
  kafka3_data:

services:
  # Base central de datos
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: insta
      POSTGRES_PASSWORD: insta123
      POSTGRES_DB: instashop
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - instashop-net

  # CRM Database
  crm-db:
    image: postgres:15
    container_name: crm_db
    environment:
      POSTGRES_USER: crm
      POSTGRES_PASSWORD: crm123
      POSTGRES_DB: crm_db
    ports:
      - "5433:5432"
    volumes:
      - ./data/crm:/var/lib/postgresql/data
    networks:
      - instashop-net

  # ERP Database
  erp-db:
    image: postgres:15
    container_name: erp_db
    environment:
      POSTGRES_USER: erp
      POSTGRES_PASSWORD: erp123
      POSTGRES_DB: erp_db
    ports:
      - "5434:5432"
    volumes:
      - ./data/erp:/var/lib/postgresql/data
    networks:
      - instashop-net

  # E-commerce Database
  ecommerce-db:
    image: postgres:15
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: ecommerce
      POSTGRES_PASSWORD: ecommerce123
      POSTGRES_DB: ecommerce_db
    ports:
      - "5435:5432"
    volumes:
      - ./data/ecommerce:/var/lib/postgresql/data
    networks:
      - instashop-net

  # Data Warehouse
  dwh-db:
    image: postgres:15
    container_name: dwh_db
    environment:
      POSTGRES_USER: dwh
      POSTGRES_PASSWORD: dwh123
      POSTGRES_DB: dwh_db
    ports:
      - "5436:5432"
    volumes:
      - ./data/dwh:/var/lib/postgresql/data
    networks:
      - instashop-net

  # Kafka Cluster
  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka1
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CLUSTER_ID: instashop-cluster-1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9092:9092"
    volumes:
      - kafka1_data:/bitnami/kafka/data
    networks:
      - instashop-net
    healthcheck:
      test: ["CMD", "kafka-topics.sh", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka2
    environment:
      KAFKA_CFG_NODE_ID: 2
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CLUSTER_ID: instashop-cluster-2
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "2@kafka2:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9093:9092"
    volumes:
      - kafka2_data:/bitnami/kafka/data
    networks:
      - instashop-net

  kafka3:
    image: bitnami/kafka:latest
    container_name: kafka3
    environment:
      KAFKA_CFG_NODE_ID: 3
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CLUSTER_ID: instashop-cluster-3
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "3@kafka3:9093"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    ports:
      - "9094:9092"
    volumes:
      - kafka3_data:/bitnami/kafka/data
    networks:
      - instashop-net

  # Spark Master
  spark:
    image: bitnami/spark:latest
    container_name: spark
    environment:
      SPARK_MODE: master
    ports:
      - "7077:7077"
      - "8080:8080"
    volumes:
      - ./spark-app:/opt/spark-app
      - ./:/app  # Volumen para ETL scripts
    networks:
      - instashop-net

  # Jupyter con PySpark
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./spark-app:/home/jovyan/work
    networks:
      - instashop-net
